/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List local tracks */
        get: operations["list_library_tracks_api_v1_library_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the household profiles
         * @description Every profile, name-folded order.
         *
         *     The list is small and bounded by household use, so it is served whole; the
         *     page envelope is present for shape consistency, never for paging.
         */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        /** Create a household profile */
        post: operations["create_profile_api_v1_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Container readiness probe
         * @description Readiness only.
         *
         *     Redis or provider degradation deliberately does not fail this probe: the
         *     library must stay readable when acquisition cannot run.
         */
        get: operations["read_health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report readiness, degradation, storage, tools, and provider state */
        get: operations["read_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{track_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream one local track */
        get: operations["stream_track_api_v1_tracks__track_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComponentStatusModel */
        ComponentStatusModel: {
            /**
             * Detail
             * @description Short operator-facing explanation. Never contains a secret or path.
             */
            detail?: string | null;
            /**
             * Health
             * @enum {string}
             */
            health: "ok" | "degraded" | "unavailable";
            /**
             * Name
             * @description Stable component identifier.
             */
            name: string;
        };
        /** CreateProfileRequest */
        CreateProfileRequest: {
            /**
             * Name
             * @description Household profile name. Unique after case and whitespace folding.
             */
            name: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable error code.
             */
            code: string;
            /**
             * Detail
             * @description Allowlisted, redacted diagnostic context.
             */
            detail?: {
                [key: string]: unknown;
            };
            /**
             * Field
             * @description Request field that failed validation, when applicable.
             */
            field?: string | null;
            /**
             * Message
             * @description Safe, operator-facing description of the failure.
             */
            message: string;
            /**
             * Request Id
             * @description Correlates this response with stdout logs.
             */
            request_id: string;
            /**
             * Retryable
             * @description Whether repeating the same request may succeed.
             */
            retryable: boolean;
        };
        /**
         * ErrorResponse
         * @description The documented error envelope for every non-2xx API response.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthModel */
        HealthModel: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * LibrarySort
         * @description The orderings `GET /library/tracks` accepts.
         * @enum {string}
         */
        LibrarySort: "recent" | "title" | "artist";
        /** PageModel[ProfileModel] */
        PageModel_ProfileModel_: {
            /** Items */
            items: components["schemas"]["ProfileModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /** PageModel[TrackSummaryModel] */
        PageModel_TrackSummaryModel_: {
            /** Items */
            items: components["schemas"]["TrackSummaryModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /**
         * ProfileModel
         * @description One household profile.
         */
        ProfileModel: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProviderStatusModel */
        ProviderStatusModel: {
            /** Configured */
            configured: boolean;
            /** Enabled */
            enabled: boolean;
            /** Name */
            name: string;
        };
        /**
         * SystemStatusModel
         * @description The documented `GET /system/status` success envelope.
         */
        SystemStatusModel: {
            /**
             * Checked At
             * @description RFC 3339 UTC timestamp of this evaluation.
             */
            checked_at: string;
            database: components["schemas"]["ComponentStatusModel"];
            /**
             * Degraded
             * @description Acquisition is impaired by Redis or tool state. Local use is unaffected.
             */
            degraded: boolean;
            /**
             * Environment
             * @enum {string}
             */
            environment: "production" | "gate";
            /** Providers */
            providers: components["schemas"]["ProviderStatusModel"][];
            /**
             * Ready
             * @description Valid configuration, migrated database, and writable mounted roots.
             */
            ready: boolean;
            redis: components["schemas"]["ComponentStatusModel"];
            /** Storage */
            storage: components["schemas"]["ComponentStatusModel"][];
            /** Tools */
            tools: components["schemas"]["ComponentStatusModel"][];
        };
        /**
         * TrackSummaryModel
         * @description One local track as the library, search, and context views render it.
         */
        TrackSummaryModel: {
            /** Album */
            album: string | null;
            /**
             * Album Key
             * @description Derived key addressing this track's album context.
             */
            album_key: string;
            /** Artist */
            artist: string;
            /**
             * Artist Key
             * @description Derived key addressing this track's artist context.
             */
            artist_key: string;
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "missing" | "mutating" | "recovery";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disc Number */
            disc_number: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Id */
            id: string;
            /**
             * Is Playable
             * @description Whether the managed file can be streamed right now. False disables Play.
             */
            is_playable: boolean;
            /** Release Year */
            release_year: number | null;
            /** Revision */
            revision: number;
            /** Title */
            title: string;
            /** Track Number */
            track_number: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_library_tracks_api_v1_library_tracks_get: {
        parameters: {
            query?: {
                /** @description Match against normalized artist, title, and album. */
                q?: string | null;
                /** @description Ordering for this listing. */
                sort?: components["schemas"]["LibrarySort"];
                /** @description Cursor from a previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_TrackSummaryModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_ProfileModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_profile_api_v1_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_system_status_api_v1_system_status_get: {
        parameters: {
            query?: {
                /** @description Re-probe external tools instead of using the cached result. */
                refresh_tools?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_track_api_v1_tracks__track_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track ID. */
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The complete audio file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description The requested byte range. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
