/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artwork/stages/lastfm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage Last.fm's best cover for one track */
        post: operations["stage_artwork_from_lastfm_api_v1_artwork_stages_lastfm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artwork/stages/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stage an uploaded cover image
         * @description Validate and normalize one uploaded image into a single-use stage.
         *
         *     The upload is bounded before it is read whole: an oversized file is refused
         *     from its declared size rather than after the server has buffered it.
         */
        post: operations["stage_uploaded_artwork_api_v1_artwork_stages_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artwork/stages/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage a cover image from a link */
        post: operations["stage_artwork_from_url_api_v1_artwork_stages_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List downloads, newest first */
        get: operations["list_downloads_api_v1_downloads_get"];
        put?: never;
        /**
         * Queue one acquisition
         * @description Validate, durably queue, and dispatch one download.
         */
        post: operations["create_download_api_v1_downloads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one download and its event history */
        get: operations["read_download_api_v1_downloads__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream job, library, and system invalidations */
        get: operations["stream_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List local tracks */
        get: operations["list_library_tracks_api_v1_library_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect one Spotify track or YouTube video link
         * @description Recognize and inspect one link, reporting its candidate and review need.
         */
        post: operations["inspect_link_api_v1_links_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one playlist and its tracks in saved order */
        get: operations["read_playlist_api_v1_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename one playlist
         * @description Rename under the submitted revision, so a concurrent rename is visible.
         */
        patch: operations["rename_playlist_api_v1_playlists__playlist_id__patch"];
        trace?: never;
    };
    "/api/v1/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add one track to the end of a playlist */
        post: operations["add_playlist_track_api_v1_playlists__playlist_id__tracks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the household profiles
         * @description Every profile, name-folded order.
         *
         *     The list is small and bounded by household use, so it is served whole; the
         *     page envelope is present for shape consistency, never for paging.
         */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        /** Create a household profile */
        post: operations["create_profile_api_v1_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List one profile's playlists
         * @description Every playlist of one profile, most recently changed first.
         *
         *     The list is bounded by household use, so it is served whole; the page
         *     envelope is present for shape consistency, never for paging.
         */
        get: operations["list_playlists_api_v1_profiles__profile_id__playlists_get"];
        put?: never;
        /** Create a playlist for one profile */
        post: operations["create_playlist_api_v1_profiles__profile_id__playlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/deezer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Deezer for matching tracks
         * @description Return normalized, non-playable candidates and their duplicate links.
         *
         *     The page is deliberately single: ARCHITECTURE ignores Deezer pagination
         *     beyond the first page in v1, so `next_cursor` is always null rather than a
         *     cursor that cannot be honoured.
         */
        get: operations["search_deezer_api_v1_search_deezer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Container readiness probe
         * @description Readiness only.
         *
         *     Redis or provider degradation deliberately does not fail this probe: the
         *     library must stay readable when acquisition cannot run.
         */
        get: operations["read_health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report readiness, degradation, storage, tools, and provider state */
        get: operations["read_system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one complete editable track
         * @description Everything S13 needs before it enables its fields.
         */
        get: operations["read_track_api_v1_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct one track atomically
         * @description Apply the complete corrected record — tags, art, path, and row — as one change.
         *
         *     `If-Match` is required rather than optional: without it a save would
         *     silently overwrite whatever the other browser tab in the house just wrote,
         *     and this is the one mutation that also rewrites a file on disk.
         */
        patch: operations["update_track_api_v1_tracks__track_id__patch"];
        trace?: never;
    };
    "/api/v1/tracks/{track_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream one local track */
        get: operations["stream_track_api_v1_tracks__track_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/artwork/stages/{stage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve one staged cover for preview
         * @description The image the person picked, so S13 can show it before anything is saved.
         */
        get: operations["read_staged_artwork_media_artwork_stages__stage_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/artwork/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve one track's managed cover
         * @description The cover for one track, resolved through the same containment rules as audio.
         */
        get: operations["read_track_artwork_media_artwork_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddPlaylistTrackRequest
         * @description One row action: append a local track to the end of the saved order.
         */
        AddPlaylistTrackRequest: {
            /** Revision */
            revision: number;
            /** Track Id */
            track_id: string;
        };
        /**
         * ArtworkLastfmRequest
         * @description Stage Last.fm's best cover for one track's identity.
         */
        ArtworkLastfmRequest: {
            /** Album */
            album?: string | null;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
        };
        /**
         * ArtworkStageModel
         * @description One staged cover image, waiting to be consumed by a save.
         */
        ArtworkStageModel: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             * @description After this moment the stage is gone and the image must be chosen again.
             */
            expires_at: string;
            /** Id */
            id: string;
            /**
             * Mime Type
             * @constant
             */
            mime_type: "image/jpeg";
            /**
             * Origin
             * @enum {string}
             */
            origin: "upload" | "url" | "lastfm";
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * ArtworkUrlRequest
         * @description Stage the image at one submitted link.
         */
        ArtworkUrlRequest: {
            /** Url */
            url: string;
        };
        /** Body_stage_uploaded_artwork_api_v1_artwork_stages_upload_post */
        Body_stage_uploaded_artwork_api_v1_artwork_stages_upload_post: {
            /**
             * File
             * @description The cover image to stage.
             */
            file: string;
        };
        /** ComponentStatusModel */
        ComponentStatusModel: {
            /**
             * Detail
             * @description Short operator-facing explanation. Never contains a secret or path.
             */
            detail?: string | null;
            /**
             * Health
             * @enum {string}
             */
            health: "ok" | "degraded" | "unavailable";
            /**
             * Name
             * @description Stable component identifier.
             */
            name: string;
        };
        /**
         * CreatePlaylistRequest
         * @description S16, creating. Only the name is editable.
         */
        CreatePlaylistRequest: {
            /** Name */
            name: string;
        };
        /** CreateProfileRequest */
        CreateProfileRequest: {
            /**
             * Name
             * @description Household profile name. Unique after case and whitespace folding.
             */
            name: string;
        };
        /**
         * DownloadRequestModel
         * @description One immutable acquisition request.
         *
         *     The candidate is echoed back from a search result rather than re-fetched:
         *     what the person saw when they pressed Download is exactly what is stored
         *     and later acquired.
         */
        DownloadRequestModel: {
            candidate: components["schemas"]["TrackCandidateModel"];
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "deezer_result" | "spotify_track" | "youtube_video";
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Stable machine-readable error code.
             */
            code: string;
            /**
             * Detail
             * @description Allowlisted, redacted diagnostic context.
             */
            detail?: {
                [key: string]: unknown;
            };
            /**
             * Field
             * @description Request field that failed validation, when applicable.
             */
            field?: string | null;
            /**
             * Message
             * @description Safe, operator-facing description of the failure.
             */
            message: string;
            /**
             * Request Id
             * @description Correlates this response with stdout logs.
             */
            request_id: string;
            /**
             * Retryable
             * @description Whether repeating the same request may succeed.
             */
            retryable: boolean;
        };
        /**
         * ErrorResponse
         * @description The documented error envelope for every non-2xx API response.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthModel */
        HealthModel: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * JobDetailModel
         * @description One job together with its complete replayable history.
         */
        JobDetailModel: {
            /** Events */
            events: components["schemas"]["JobEventModel"][];
            job: components["schemas"]["JobModel"];
        };
        /**
         * JobEventModel
         * @description One durable, replayable step in a job's history.
         */
        JobEventModel: {
            /**
             * Id
             * @description The SSE event ID. The browser's cursor tracks this sequence.
             */
            id: number;
            /** Job Id */
            job_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: string | number | boolean;
            };
            /**
             * Phase
             * @enum {string}
             */
            phase: "accepted" | "inspecting" | "queued" | "restarted" | "downloading" | "converting" | "enriching" | "tagging" | "organizing" | "completed" | "failed" | "cancelled";
            /** Progress Percent */
            progress_percent: number | null;
            /** Sequence */
            sequence: number;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "completed" | "failed" | "cancelled";
        };
        /**
         * JobModel
         * @description One download as the Downloads screen and the job indicator render it.
         */
        JobModel: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Display State
             * @description Derived state: distinguishes a retry and a restart from a first attempt.
             * @enum {string}
             */
            display_state: "queued" | "retrying" | "restarted" | "running" | "completed" | "failed" | "cancelled";
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Parent Job Id */
            parent_job_id: string | null;
            /**
             * Phase
             * @enum {string}
             */
            phase: "accepted" | "inspecting" | "queued" | "restarted" | "downloading" | "converting" | "enriching" | "tagging" | "organizing" | "completed" | "failed" | "cancelled";
            /**
             * Progress Percent
             * @description Null when the provider reports no real percentage. Never invented.
             */
            progress_percent: number | null;
            /**
             * Provider
             * @enum {string}
             */
            provider: "deezer" | "spotdl" | "yt_dlp";
            /** Restart Count */
            restart_count: number;
            /** Result Track Id */
            result_track_id: string | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "deezer_result" | "spotify_track" | "youtube_video";
            /** Started At */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "completed" | "failed" | "cancelled";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * LibrarySort
         * @description The orderings `GET /library/tracks` accepts.
         * @enum {string}
         */
        LibrarySort: "recent" | "title" | "artist";
        /**
         * LinkInspectionModel
         * @description What one link resolves to, and how it should be queued.
         *
         *     `source_type` is always `spotify_track` or `youtube_video` in practice —
         *     inspection only recognizes those two — and the wire literal is shared with
         *     the download request so the same candidate flows straight into it.
         */
        LinkInspectionModel: {
            candidate: components["schemas"]["TrackCandidateModel"];
            /**
             * Existing Track Id
             * @description The local track this link already duplicates, if any.
             */
            existing_track_id?: string | null;
            /**
             * Is Playable
             * @description Always false. A link resolves to something to acquire, never a local file.
             * @default false
             * @constant
             */
            is_playable: false;
            /**
             * Provider
             * @enum {string}
             */
            provider: "deezer" | "spotdl" | "yt_dlp";
            /**
             * Review Required
             * @description True when S5 metadata review must precede queueing, as for YouTube.
             */
            review_required: boolean;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "deezer_result" | "spotify_track" | "youtube_video";
        };
        /**
         * LinkInspectionRequest
         * @description One submitted URL to recognize and inspect.
         */
        LinkInspectionRequest: {
            /**
             * Url
             * @description The submitted link.
             */
            url: string;
        };
        /** PageModel[JobModel] */
        PageModel_JobModel_: {
            /** Items */
            items: components["schemas"]["JobModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /** PageModel[PlaylistModel] */
        PageModel_PlaylistModel_: {
            /** Items */
            items: components["schemas"]["PlaylistModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /** PageModel[ProfileModel] */
        PageModel_ProfileModel_: {
            /** Items */
            items: components["schemas"]["ProfileModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /** PageModel[RemoteResultModel] */
        PageModel_RemoteResultModel_: {
            /** Items */
            items: components["schemas"]["RemoteResultModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /** PageModel[TrackSummaryModel] */
        PageModel_TrackSummaryModel_: {
            /** Items */
            items: components["schemas"]["TrackSummaryModel"][];
            /**
             * Next Cursor
             * @description Opaque cursor for the next page, or null when this page is the last.
             */
            next_cursor?: string | null;
        };
        /**
         * PlaylistDetailModel
         * @description One playlist and its tracks in saved order.
         */
        PlaylistDetailModel: {
            playlist: components["schemas"]["PlaylistModel"];
            /** Tracks */
            tracks: components["schemas"]["TrackSummaryModel"][];
        };
        /**
         * PlaylistModel
         * @description One playlist as the sidebar and S9 render it.
         */
        PlaylistModel: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Profile Id */
            profile_id: string;
            /**
             * Revision
             * @description Supply as `revision` on the next change to this playlist.
             */
            revision: number;
            /** Track Count */
            track_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProfileModel
         * @description One household profile.
         */
        ProfileModel: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProviderStatusModel */
        ProviderStatusModel: {
            /** Configured */
            configured: boolean;
            /** Enabled */
            enabled: boolean;
            /** Name */
            name: string;
        };
        /**
         * RemoteResultModel
         * @description One search result, and the local track it duplicates when there is one.
         */
        RemoteResultModel: {
            candidate: components["schemas"]["TrackCandidateModel"];
            /**
             * Existing Track Id
             * @description The local track this result already duplicates, if any.
             */
            existing_track_id?: string | null;
            /**
             * Is Playable
             * @description Always false. A remote result has no local file, so no screen offers Play.
             * @default false
             * @constant
             */
            is_playable: false;
        };
        /**
         * RenamePlaylistRequest
         * @description S16, renaming. The revision is what makes a concurrent rename visible.
         */
        RenamePlaylistRequest: {
            /** Name */
            name: string;
            /** Revision */
            revision: number;
        };
        /**
         * SystemStatusModel
         * @description The documented `GET /system/status` success envelope.
         */
        SystemStatusModel: {
            /**
             * Checked At
             * @description RFC 3339 UTC timestamp of this evaluation.
             */
            checked_at: string;
            database: components["schemas"]["ComponentStatusModel"];
            /**
             * Degraded
             * @description Acquisition is impaired by Redis or tool state. Local use is unaffected.
             */
            degraded: boolean;
            /**
             * Environment
             * @enum {string}
             */
            environment: "production" | "gate";
            /** Providers */
            providers: components["schemas"]["ProviderStatusModel"][];
            /**
             * Ready
             * @description Valid configuration, migrated database, and writable mounted roots.
             */
            ready: boolean;
            redis: components["schemas"]["ComponentStatusModel"];
            /** Storage */
            storage: components["schemas"]["ComponentStatusModel"][];
            /** Tools */
            tools: components["schemas"]["ComponentStatusModel"][];
        };
        /**
         * TrackCandidateModel
         * @description One normalized remote candidate, from any provider, in one shape.
         */
        TrackCandidateModel: {
            /** Acquisition Locator */
            acquisition_locator: string;
            /** Album */
            album: string | null;
            /** Artist */
            artist: string;
            /** Artwork Url */
            artwork_url: string | null;
            /** Disc Number */
            disc_number: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Isrc */
            isrc: string | null;
            /** Provider */
            provider: string;
            /** Raw Fingerprint */
            raw_fingerprint: string | null;
            /** Release Year */
            release_year: number | null;
            /** Source Id */
            source_id: string | null;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
            /** Track Number */
            track_number: number | null;
        };
        /**
         * TrackDetailModel
         * @description The complete editable record S13 loads before it enables its fields.
         */
        TrackDetailModel: {
            /**
             * Has Artwork
             * @description Whether a managed cover exists. Its bytes are served by the artwork route.
             */
            has_artwork: boolean;
            /** Sources */
            sources: components["schemas"]["TrackSourceModel"][];
            track: components["schemas"]["TrackSummaryModel"];
        };
        /**
         * TrackSourceModel
         * @description One provider identity a track was acquired from.
         *
         *     Disclosed on S13 because a person correcting metadata benefits from seeing
         *     where the file came from; it is never used to address the track.
         */
        TrackSourceModel: {
            /** Provider */
            provider: string;
            /** Source Id */
            source_id: string | null;
            /** Source Url */
            source_url: string;
        };
        /**
         * TrackSummaryModel
         * @description One local track as the library, search, and context views render it.
         */
        TrackSummaryModel: {
            /** Album */
            album: string | null;
            /**
             * Album Key
             * @description Derived key addressing this track's album context.
             */
            album_key: string;
            /** Artist */
            artist: string;
            /**
             * Artist Key
             * @description Derived key addressing this track's artist context.
             */
            artist_key: string;
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "missing" | "mutating" | "recovery";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disc Number */
            disc_number: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Id */
            id: string;
            /**
             * Is Playable
             * @description Whether the managed file can be streamed right now. False disables Play.
             */
            is_playable: boolean;
            /** Release Year */
            release_year: number | null;
            /** Revision */
            revision: number;
            /** Title */
            title: string;
            /** Track Number */
            track_number: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UpdateTrackRequest
         * @description The complete intended record for one save.
         *
         *     Every editable field is required rather than optional: a partial patch
         *     would make "clear the album" and "leave the album alone" indistinguishable,
         *     and the save has to rewrite the file's tags either way.
         */
        UpdateTrackRequest: {
            /** Album */
            album?: string | null;
            /** Artist */
            artist: string;
            /**
             * Artwork Stage Id
             * @description A staged cover to consume atomically with this save.
             */
            artwork_stage_id?: string | null;
            /** Disc Number */
            disc_number?: number | null;
            /** Release Year */
            release_year?: number | null;
            /** Title */
            title: string;
            /** Track Number */
            track_number?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stage_artwork_from_lastfm_api_v1_artwork_stages_lastfm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtworkLastfmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkStageModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stage_uploaded_artwork_api_v1_artwork_stages_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_stage_uploaded_artwork_api_v1_artwork_stages_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkStageModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stage_artwork_from_url_api_v1_artwork_stages_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtworkUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkStageModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_downloads_api_v1_downloads_get: {
        parameters: {
            query?: {
                /** @description Restrict the listing to these durable states. */
                state?: ("queued" | "running" | "completed" | "failed" | "cancelled")[] | null;
                /** @description Cursor from a previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_JobModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_download_api_v1_downloads_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequestModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_download_api_v1_downloads__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Cursor fallback for clients that cannot set the header. */
                last_event_id?: string | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_library_tracks_api_v1_library_tracks_get: {
        parameters: {
            query?: {
                /** @description Match against normalized artist, title, and album. */
                q?: string | null;
                /** @description Ordering for this listing. */
                sort?: components["schemas"]["LibrarySort"];
                /** @description Cursor from a previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_TrackSummaryModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inspect_link_api_v1_links_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkInspectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkInspectionModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_playlist_api_v1_playlists__playlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist ID. */
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetailModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_playlist_api_v1_playlists__playlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist ID. */
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenamePlaylistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_playlist_track_api_v1_playlists__playlist_id__tracks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist ID. */
                playlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPlaylistTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetailModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_ProfileModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_profile_api_v1_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_playlists_api_v1_profiles__profile_id__playlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile ID. */
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_PlaylistModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_playlist_api_v1_profiles__profile_id__playlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile ID. */
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaylistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_deezer_api_v1_search_deezer_get: {
        parameters: {
            query: {
                /** @description The submitted query. */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageModel_RemoteResultModel_"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_system_status_api_v1_system_status_get: {
        parameters: {
            query?: {
                /** @description Re-probe external tools instead of using the cached result. */
                refresh_tools?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_track_api_v1_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track ID. */
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetailModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_track_api_v1_tracks__track_id__patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description The track's current `revision`. */
                "If-Match"?: string | null;
            };
            path: {
                /** @description Track ID. */
                track_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetailModel"];
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_track_api_v1_tracks__track_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track ID. */
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The complete audio file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description The requested byte range. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_staged_artwork_media_artwork_stages__stage_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Artwork stage ID. */
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The staged image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_track_artwork_media_artwork_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track ID. */
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cover image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
