#!/usr/bin/env bash
#
# Create a disposable gate environment.
#
#   ./scripts/gate/prepare.sh <name> [mode]
#
# Everything it creates lives under .gate/<name>/. It refuses to touch any
# path outside that tree, so a gate run can never reach household data.
#
# `mode` selects the runtime environment:
#   production (default)  real adapters, ordinary Redis prefix, no containment
#                          root declared (a real household deployment never
#                          looks disposable)
#   gate                   fixture adapters, chillify:gate:<name>: prefix,
#                          declared containment root
#   release                real adapters (the unchanged production
#                          composition, never fixtures), but a provably
#                          disposable tree: chillify:gate:<name>: prefix and a
#                          declared containment root, exactly like gate mode,
#                          so it can be seeded and torn down the same way.
#                          This is what Task 20's release gate needs: the
#                          real composition, seeded.

set -Eeuo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NAME="${1:-}"
MODE="${2:-production}"

if [[ -z "$NAME" ]]; then
    printf 'usage: %s <name> [production|gate|release]\n' "$0" >&2
    exit 2
fi

if [[ ! "$NAME" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
    printf 'prepare: gate name must be lowercase alphanumeric with dashes\n' >&2
    exit 2
fi

case "$MODE" in
    production | gate | release) ;;
    *)
        printf 'prepare: mode must be production, gate, or release\n' >&2
        exit 2
        ;;
esac

GATE_ROOT="$REPO_ROOT/.gate/$NAME"

# Fail closed: the resolved target must stay beneath the repository .gate tree.
RESOLVED_PARENT="$(cd "$REPO_ROOT" && mkdir -p .gate && cd .gate && pwd -P)"
case "$(cd "$(dirname "$GATE_ROOT")" && pwd -P)" in
    "$RESOLVED_PARENT") ;;
    *)
        printf 'prepare: refusing to write outside %s\n' "$RESOLVED_PARENT" >&2
        exit 1
        ;;
esac

mkdir -p "$GATE_ROOT/data" "$GATE_ROOT/music" "$GATE_ROOT/fixtures"

if [[ "$MODE" == "gate" ]]; then
    REDIS_PREFIX="chillify:gate:${NAME}:"
    FIXTURE_ROOT="$GATE_ROOT/fixtures"
    # The containment root every other gate root must live beneath. These are
    # host paths, used by host-process runs and as the Compose bind sources;
    # the gate overlay replaces them with the container's own paths.
    CONTAINMENT_ROOT="$GATE_ROOT"
    # The disposable Redis the gate overlay supplies, addressed by its service
    # name on the Compose network. A caller running the app on the host instead
    # of in containers overrides REDIS_URL to reach their own Redis.
    DEFAULT_REDIS_URL="redis://redis:6379/0"
    # Seed the fixture adapters' recorded payloads. They are copied rather
    # than referenced so a gate run reads only from its own disposable tree.
    cp -R "$REPO_ROOT/backend/tests/fixtures/." "$GATE_ROOT/fixtures/"
elif [[ "$MODE" == "release" ]]; then
    # Real adapters (CHILLIFY_ENV=release never binds fixtures — `is_gate`
    # stays false), but still a provably disposable environment: no
    # CHILLIFY_FIXTURE_ROOT (fixture adapters must never bind), and a
    # declared CHILLIFY_GATE_ROOT so config.py's containment check and
    # scripts/gate/seed.sh's own re-check have a boundary to verify against.
    # Task 20's own preflight paragraph names the Redis prefix
    # `chillify:gate:release:`, so this reuses gate's isolated Redis
    # namespace even though this is the real production composition.
    REDIS_PREFIX="chillify:gate:${NAME}:"
    FIXTURE_ROOT=""
    CONTAINMENT_ROOT="$GATE_ROOT"
    # Release launches through the unchanged compose.yaml, which has no redis
    # service of its own (same as production) — see the production branch's
    # comment below for why host.docker.internal is required here.
    DEFAULT_REDIS_URL="redis://host.docker.internal:6379/0"
else
    REDIS_PREFIX="chillify:"
    FIXTURE_ROOT=""
    CONTAINMENT_ROOT=""
    # Production mode supplies no Redis of its own: compose.yaml has no redis
    # service, so the operator's own Redis runs on the Docker host. Inside the
    # api/worker containers 127.0.0.1 is the container itself, which is why the
    # backend addresses the host through the host.docker.internal alias
    # compose.yaml maps to host-gateway. A caller running the app as a host
    # process instead of in containers overrides REDIS_URL with a loopback URL.
    DEFAULT_REDIS_URL="redis://host.docker.internal:6379/0"
fi

SECRET_KEY="$(
    python3 -c 'import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'
)"

cat > "$GATE_ROOT/.env" <<EOF
# Generated by scripts/gate/prepare.sh for the disposable "$NAME" environment.
# Not household configuration. Safe to delete with the rest of .gate/$NAME.
CHILLIFY_BIND_PORT=${CHILLIFY_BIND_PORT:-8788}
CHILLIFY_DATA_ROOT=$GATE_ROOT/data
CHILLIFY_MUSIC_ROOT=$GATE_ROOT/music
CHILLIFY_UID=$(id -u)
CHILLIFY_GID=$(id -g)
REDIS_URL=${REDIS_URL:-$DEFAULT_REDIS_URL}
CHILLIFY_REDIS_PREFIX=$REDIS_PREFIX
CHILLIFY_SECRET_KEY=$SECRET_KEY
CHILLIFY_LOG_LEVEL=${CHILLIFY_LOG_LEVEL:-INFO}
CHILLIFY_ALLOWED_ORIGINS=
CHILLIFY_ENV=$MODE
CHILLIFY_FIXTURE_ROOT=$FIXTURE_ROOT
CHILLIFY_GATE_ROOT=$CONTAINMENT_ROOT
EOF

chmod 0600 "$GATE_ROOT/.env"

printf 'prepared %s (%s)\n' "$GATE_ROOT" "$MODE"
if [[ "$MODE" == "gate" ]]; then
    # A gate launches the production composition plus the fixture overlay.
    # Without the overlay the fixture payloads are not mounted and startup
    # fails closed, which is the intended outcome rather than a silent
    # fixture-less run.
    printf 'launch: docker compose --env-file .gate/%s/.env -f compose.yaml -f deploy/compose.gate.yaml up --build -d\n' \
        "$NAME"
else
    printf 'launch: docker compose --env-file .gate/%s/.env up --build -d\n' "$NAME"
fi
